version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/db/Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: db-pass
    ports:
      - 5432:5432
    volumes:
      - emolecules_db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "4.00"
          memory: 2g
        reservations:
          cpus: "3.00"
          memory: 1g
  service:
    build:
      context: .
      dockerfile: dockerfiles/service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "/wait && ./example-postgresql-exe"
    environment:
      CONFIG_PROFILE: local-docker
volumes:
  emolecules_db:
