version: '3'

services:
  db:
    image: informaticsmatters/rdkit-cartridge-debian
    restart: always
    environment:
      POSTGRES_PASSWORD: db-pass
    ports:
      - 5432:5432

  service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "/wait && ./example-postgresql-exe"
    environment:
      CONFIG_PROFILE: local-docker
